### ISSUE TITLE
Failed to complete #setup action:

### ISSUE THREAD

**Issue by milky-milk** [neillturner/kitchen-verifier-serverspec#1]
Hello!
I'm trying to setup test-kitchen with docker driver, kitchen-ansible and kitchen-verifier-serverspec, but it dies with error: 
```
-----> Starting Kitchen (v1.6.0)
D      [kitchen::driver::docker command] BEGIN (sudo -E docker >> /dev/null 2>&1)
D      [kitchen::driver::docker command] END (0m0.11s)
-----> Setting up <default-centos-67>...
$$$$$$ Running legacy setup for 'Docker' Driver
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #setup action: [private method `install_command' called for #<Kitchen::Verifier::Serverspec:0x000000020e3c40>]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #setup action: [private method `install_command' called for #<Kitchen::Verifier::Serverspec:0x000000020e3c40>]
D      ---Nested Exception---
D      Class: NoMethodError
D      Message: private method `install_command' called for #<Kitchen::Verifier::Serverspec:0x000000020e3c40>
D      ------Backtrace-------
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/driver/ssh_base.rb:95:in `block in setup'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/transport/base.rb:86:in `initialize'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/transport/ssh.rb:350:in `new'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/transport/ssh.rb:350:in `create_new_connection'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/transport/ssh.rb:85:in `connection'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/driver/ssh_base.rb:94:in `setup'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:602:in `legacy_ssh_base_setup'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:388:in `block in setup_action'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `call'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:478:in `block in action'
D      /usr/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:477:in `action'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:387:in `setup_action'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `each'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `transition_to'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:160:in `verify'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `public_send'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
```

My kitchen.yml
```
---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  playbook: site.yml
  require_ansible_repo: true
  require_ruby_for_busser: true

platforms:
  - name: centos-6.7

verifier:
  name: serverspec
  sudo_path: true
  remote_execution: true

suites:
  - name: default
    run_list:
    attributes:
```

and my installed gems:

```
*** LOCAL GEMS ***

backticks (0.4.0)
bigdecimal (1.2.4)
bundler (1.11.2)
diff-lcs (1.2.5)
docker (0.3.1)
faraday (0.9.2)
highline (1.7.8)
io-console (0.4.2)
json (1.8.1)
kitchen-ansible (0.40.1, 0.0.32)
kitchen-docker (2.3.0, 1.5.0)
kitchen-verifier-serverspec (0.3.0)
librarian (0.1.2)
librarian-ansible (3.0.0)
minitest (4.7.5)
mixlib-install (0.7.1)
mixlib-shellout (2.2.6, 1.6.1)
multi_json (1.11.2)
multipart-post (2.0.0)
net-scp (1.2.1)
net-ssh (2.9.4)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
rspec (3.4.0)
rspec-core (3.4.4)
rspec-expectations (3.4.0)
rspec-its (1.2.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
safe_yaml (1.0.4)
serverspec (2.3.1)
specinfra (2.4.5)
test-kitchen (1.6.0, 1.2.1)
test-unit (2.1.5.0)
thor (0.19.1)
```

Where I am wrong? Maybe I am miss something? 

Thanks

**Comment by neillturner** [comment]
Is it failing on the 
  kitchen create   command 
if so it would be just a kitchen docker issue. you can remove the provisioner and verifier sections on the kitchen command and see why kitchen docker is failing.

if it is on the kitchen converge command then it is an issue when kitchen-ansible but i don't see any privisioner code in the Backtrace

**Comment by milky-milk** [comment]
Thanks for answer. 

> if so it would be just a kitchen docker issue. you can remove the provisioner and verifier sections on the kitchen command and see why kitchen docker is failing.

I've destroyed kitchen, removed the provisioner and verifier sections from .kitchen.yml, but now it seems it fails when trying to install busser when I run `kitchen test`

```
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
       Successfully installed thor-0.19.0
Fetching: busser-0.7.1.gem (100%)
       Successfully installed busser-0.7.1
       2 gems installed
       Installing Busser plugins: busser-serverspec busser-spec
       Plugin serverspec installed (version 0.5.9)
-----> Running postinstall for serverspec plugin
       /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/resolver/installer_set.rb:71:in `add_always_install': Unable to resolve dependency: user requested 'busser-spec (>= 0)' (Gem::UnsatisfiableDependencyError)
       	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
       	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency_installer.rb:384:in `install'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/rubygems.rb:44:in `install_gem'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/plugin_install.rb:66:in `install_plugin_gem'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/plugin_install.rb:53:in `install'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/plugin_install.rb:43:in `block (2 levels) in install_all'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/plugin_install.rb:43:in `each'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/plugin_install.rb:43:in `block in install_all'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/rubygems.rb:71:in `silence_gem_ui'
       	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/plugin_install.rb:42:in `install_all'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:40:in `block in register'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:235:in `block in subcommand'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
       	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
       	from /tmp/verifier/gems/gems/busser-0.7.1/bin/busser:8:in `<top (required)>'
       	from /tmp/verifier/bin/busser:22:in `load'
       	from /tmp/verifier/bin/busser:22:in `<main>'
>>>>>> Setup failed on instance <default-centos-67>.
>>>>>> Please see .kitchen/logs/default-centos-67.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri --no-format-executable -n /tmp/verifier/bin --no-user-install"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-serverspec busser-spec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  $busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
']
>>>>>> ----------------------
D      Setup failed on instance <default-centos-67>.
D      ------Exception-------
D      Class: Kitchen::InstanceFailure
D      Message: Setup failed on instance <default-centos-67>.  Please see .kitchen/logs/default-centos-67.log for more details
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE
ruby="/opt/chef/embedded/bin/ruby"
gem="/opt/chef/embedded/bin/gem"
version="busser"
gem_install_args="busser --no-rdoc --no-ri --no-format-executable -n /tmp/verifier/bin --no-user-install"
busser="sudo -E /tmp/verifier/bin/busser"
plugins="busser-serverspec busser-spec"

$gem list busser -i 2>&1 >/dev/null
if test $? -ne 0; then
  echo "-----> Installing Busser ($version)"
  $gem install $gem_install_args
else
  echo "-----> Busser installation detected ($version)"
fi

if test ! -f "$BUSSER_ROOT/bin/busser"; then
  $busser setup
fi

echo "       Installing Busser plugins: $plugins"
$busser plugin install $plugins
']
D      ------Backtrace-------
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/driver/ssh_base.rb:98:in `rescue in setup'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/driver/ssh_base.rb:92:in `setup'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:602:in `legacy_ssh_base_setup'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:388:in `block in setup_action'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `call'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:513:in `synchronize_or_call'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:478:in `block in action'
D      /usr/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:477:in `action'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:387:in `setup_action'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:348:in `block in transition_to'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `each'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:347:in `transition_to'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:160:in `verify'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:189:in `block in test'
D      /usr/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/instance.rb:185:in `test'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `public_send'
D      /var/lib/gems/2.1.0/gems/test-kitchen-1.6.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
zlib(finalizer): the stream was freed prematurely.
```

There is a full output of `kitchen test -l debug` command: http://upaste.me/411424260b9f1091d

**Comment by neillturner** [comment]
the test command runs create, converge and verify in order so its a bit tough to see where problem is run the command separately. 
 I would put the provisioner and verifier sections back in and then  run  the following commands separately  
   kitchen create -l debug 
   kitchen converge -l debug 
   kitchen verify -l debug 
and see where it fails and then we can see if it is in the driver, provisioner or verifier.

**Comment by milky-milk** [comment]
Hello. Thanks for answer.

`kitchen create -l debug` works fine: http://upaste.me/adbe24288d234fc39
`kitchen converge -l debug` forks fine: http://upaste.me/65c924289f1d35255
`kitchen verify -l debug` fails: http://upaste.me/d17a24290230a517e

```
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #setup action: [private method `install_command' called for #<Kitchen::Verifier::Serverspec:0x000000015151e8>]
D      ---Nested Exception---
D      Class: NoMethodError
D      Message: private method `install_command' called for #<Kitchen::Verifier::Serverspec:0x000000015151e8>
```
Where I can find `install_command` method and check what is wrong with it? 
Sorry, I'm not good in ruby.

**Comment by milky-milk** [comment]
`install_commmand` - there is three letters by default. Is that correct?

**Comment by neillturner** [comment]
The install command is by default  'bundle install' and there is a gemfile that bundle uses to install stuff in ruby.  
By default the Gemfile is: 

 source 'https://rubygems.org'
 gem 'net-ssh','~> 2.9'
 gem 'serverspec'

You are doing 
 remote_execution: true
so its going to install serverspec on the server (not locally on your workstation) 

I suspect the provisioner installer didn't work properly. I would logon to the docker server and check if ruby is install (ie run ruby -v)

Another think to can try is changing the verifier step to
 remote_exec: false
and run it from your workstation and see if that work. 

kitchen_verifier_serverspec is ptetty new so im sure i have not ironed out all the bugs yet. -)

**Comment by neillturner** [comment]
looks like someone found the bug: 
 https://github.com/centosadmin/kitchen-verifier-serverspec/commit/1d52c2201ecd82348162cad70967889d71be23b0

the advantage of open source.

**Comment by neillturner** [comment]
push out a fix for this. try testing it with kitchen-verifier-serverspec 0.3.1 it should work now.
 you can see  https://github.com/neillturner/ansible_repo for a sample repository to use and sample kitchen yml files.

**Comment by milky-milk** [comment]
It works fine now. Thank you!

**Comment by raphaelpaiva** [comment]
Any idea on what causes this? I'm having the same issue, but I don't know how to specify a kitchen-verifier-serverspec version :disappointed:

**Comment by neillturner** [comment]
if you enter 
  gem uninstall kitchen-verifier-serverspec
it will uninstall version and if multiple versions prompt you to uninstall 
all or select the version to uninstall 
then 
  gem install kitchen-verifier-serverspec
and will install latest version 
  to install a particular version: 
   gem install kitchen-verifier-serverspec   -v 0.5.2
